services:
  api:
    build:
      context: .
      dockerfile: ./docker/go/Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - zen-network
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/hello"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

networks:
  zen-network:
    driver: bridge
